In [1]:
import sys
import numpy as np

In [2]:
# Utility code to convery raw_input to numpy ndarrays (used for hackkerrank challenges)
# Replace input to raw_input() for hackerrank

X = np.array([])
while True:
    try:
        raw_line = input().split()

#     Comment the following two lines when using code for hackerrank challenges
        if len(raw_line) == 0:
            break

        utility_list = []
        for i in range(len(raw_line)):
            utility_list.append(float(raw_line[i]))
    
        numpy_array = np.array(utility_list)
        numpy_array = np.expand_dims(numpy_array, 0)
        
        if len(X) == 0:
            X = np.append(X,numpy_array)
            X = np.expand_dims(X, 0)
        else:
            X = np.append(X, numpy_array, axis = 0)
    
    except EOFError:
        break
        
print(X)

1 2 3
4 5 6
7 8 9

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
